"""initial_schema

Revision ID: 20260923_223607
Revises: 
Create Date: 2026-09-23T22:36:07.943782

Auto-generated by generate_migration.py from ORM metadata.
Do NOT edit manually unless you know what you are doing.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260923_223607"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- Create enums first ---
    op.execute("CREATE TYPE IF NOT EXISTS role_enum AS ENUM ('SUPER_ADMIN', 'ADMIN', 'EMPLOYEE', 'STUDENT')")
    op.execute("CREATE TYPE IF NOT EXISTS classification_enum AS ENUM ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')")
    op.execute("CREATE TYPE IF NOT EXISTS document_status_enum AS ENUM ('pending', 'processing', 'completed', 'failed', 'deleted')")
    op.execute("CREATE TYPE IF NOT EXISTS message_role_enum AS ENUM ('user', 'assistant', 'system')")

    # --- Create tables (topological order) ---
    op.create_table(
        "users",
        sa.Column("id",                     sa.String(36),  primary_key=True),
        sa.Column("name",                   sa.String(120), nullable=False),
        sa.Column("email",                  sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash",          sa.String(255), nullable=True),
        sa.Column("role",                   sa.Enum("SUPER_ADMIN","ADMIN","EMPLOYEE","STUDENT", name="role_enum"), nullable=False, server_default="EMPLOYEE"),
        sa.Column("department",             sa.String(100), nullable=True),
        sa.Column("is_active",              sa.Boolean(),   nullable=False, server_default="true"),
        sa.Column("email_verified",         sa.Boolean(),   nullable=False, server_default="false"),
        sa.Column("failed_login_attempts",  sa.Integer(),   nullable=False, server_default="0"),
        sa.Column("locked_until",           sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at",             sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at",             sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login",             sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_users_email",      "users", ["email"],      unique=True)
    op.create_index("ix_users_role",       "users", ["role"],       unique=False)
    op.create_index("ix_users_department", "users", ["department"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id",          sa.String(36), primary_key=True),
        sa.Column("name",        sa.String(50), nullable=False, unique=True),
        sa.Column("description", sa.Text(),     nullable=True),
        sa.Column("created_at",  sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "permissions",
        sa.Column("id",          sa.String(36),  primary_key=True),
        sa.Column("name",        sa.String(100), nullable=False, unique=True),
        sa.Column("description", sa.Text(),      nullable=True),
    )

    op.create_table(
        "role_permissions",
        sa.Column("role_id",       sa.String(36), sa.ForeignKey("roles.id",       ondelete="CASCADE"), primary_key=True),
        sa.Column("permission_id", sa.String(36), sa.ForeignKey("permissions.id", ondelete="CASCADE"), primary_key=True),
    )

    op.create_table(
        "user_roles",
        sa.Column("user_id",    sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("role_id",    sa.String(36), sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("granted_by", sa.String(36), sa.ForeignKey("users.id"), nullable=True),
    )

    op.create_table(
        "otp_codes",
        sa.Column("id",         sa.String(36),  primary_key=True),
        sa.Column("user_id",    sa.String(36),  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=True),
        sa.Column("email",      sa.String(255), nullable=False),
        sa.Column("otp_hash",   sa.String(255), nullable=False),
        sa.Column("purpose",    sa.String(30),  nullable=False, server_default="login"),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts",   sa.Integer(),   nullable=False, server_default="0"),
        sa.Column("is_used",    sa.Boolean(),   nullable=False, server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_otp_codes_user_id",       "otp_codes", ["user_id"],  unique=False)
    op.create_index("ix_otp_codes_email",         "otp_codes", ["email"],    unique=False)
    op.create_index("ix_otp_codes_email_created", "otp_codes", ["email", "created_at"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id",           sa.String(36),  primary_key=True),
        sa.Column("user_id",      sa.String(36),  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("jti",          sa.String(64),  nullable=False, unique=True),
        sa.Column("ip_address",   sa.String(45),  nullable=True),
        sa.Column("user_agent",   sa.String(500), nullable=True),
        sa.Column("is_revoked",   sa.Boolean(),   nullable=False, server_default="false"),
        sa.Column("expires_at",   sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at",   sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_index("ix_sessions_jti",     "sessions", ["jti"],     unique=True)

    op.create_table(
        "documents",
        sa.Column("id",                sa.String(36),   primary_key=True),
        sa.Column("filename",          sa.String(500),  nullable=False),
        sa.Column("original_filename", sa.String(500),  nullable=False),
        sa.Column("file_path",         sa.String(1000), nullable=False),
        sa.Column("file_size",         sa.Integer(),    nullable=False),
        sa.Column("file_type",         sa.String(20),   nullable=False),
        sa.Column("mime_type",         sa.String(100),  nullable=True),
        sa.Column("owner_id",          sa.String(36),   sa.ForeignKey("users.id"), nullable=False),
        sa.Column("department",        sa.String(100),  nullable=True),
        sa.Column("classification",    sa.Enum("PUBLIC","INTERNAL","CONFIDENTIAL","RESTRICTED", name="classification_enum"), nullable=False, server_default="INTERNAL"),
        sa.Column("description",       sa.Text(),       nullable=True),
        sa.Column("status",            sa.Enum("pending","processing","completed","failed","deleted", name="document_status_enum"), nullable=False, server_default="pending"),
        sa.Column("error_message",     sa.Text(),       nullable=True),
        sa.Column("chunk_count",       sa.Integer(),    nullable=True),
        sa.Column("version",           sa.Integer(),    nullable=False, server_default="1"),
        sa.Column("checksum",          sa.String(64),   nullable=True),
        sa.Column("doc_metadata",      postgresql.JSONB(), nullable=True),
        sa.Column("created_at",        sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at",        sa.DateTime(timezone=True), nullable=True),
        sa.Column("indexed_at",        sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_documents_owner_id",                   "documents", ["owner_id"],                    unique=False)
    op.create_index("ix_documents_status",                     "documents", ["status"],                      unique=False)
    op.create_index("ix_documents_classification",             "documents", ["classification"],               unique=False)
    op.create_index("ix_documents_department",                 "documents", ["department"],                   unique=False)
    op.create_index("ix_documents_owner_status",               "documents", ["owner_id", "status"],          unique=False)
    op.create_index("ix_documents_department_classification",  "documents", ["department", "classification"], unique=False)

    op.create_table(
        "document_permissions",
        sa.Column("id",          sa.String(36), primary_key=True),
        sa.Column("document_id", sa.String(36), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id",     sa.String(36), sa.ForeignKey("users.id",     ondelete="CASCADE"), nullable=True),
        sa.Column("role",        sa.Enum("SUPER_ADMIN","ADMIN","EMPLOYEE","STUDENT", name="role_enum"), nullable=True),
        sa.Column("department",  sa.String(100), nullable=True),
        sa.Column("can_read",    sa.Boolean(),  nullable=False, server_default="true"),
        sa.Column("can_delete",  sa.Boolean(),  nullable=False, server_default="false"),
        sa.Column("granted_by",  sa.String(36), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("granted_at",  sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_doc_perms_document_id", "document_permissions", ["document_id"], unique=False)
    op.create_index("ix_doc_perms_user_id",     "document_permissions", ["user_id"],     unique=False)
    op.create_index("ix_doc_perms_role",        "document_permissions", ["role"],        unique=False)
    op.create_index("ix_doc_perms_department",  "document_permissions", ["department"],  unique=False)

    op.create_table(
        "document_versions",
        sa.Column("id",          sa.String(36),   primary_key=True),
        sa.Column("document_id", sa.String(36),   sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("version",     sa.Integer(),    nullable=False),
        sa.Column("file_path",   sa.String(1000), nullable=False),
        sa.Column("file_size",   sa.Integer(),    nullable=False),
        sa.Column("checksum",    sa.String(64),   nullable=True),
        sa.Column("created_at",  sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_by",  sa.String(36),   sa.ForeignKey("users.id"), nullable=True),
    )
    op.create_index("ix_document_versions_document_id", "document_versions", ["document_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id",         sa.String(36),  primary_key=True),
        sa.Column("user_id",    sa.String(36),  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title",      sa.String(200), nullable=False, server_default="New Conversation"),
        sa.Column("is_active",  sa.Boolean(),   nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_conversations_user_id",       "conversations", ["user_id"],              unique=False)
    op.create_index("ix_conversations_user_updated",  "conversations", ["user_id", "updated_at"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id",               sa.String(36), primary_key=True),
        sa.Column("conversation_id",  sa.String(36), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role",             sa.Enum("user","assistant","system", name="message_role_enum"), nullable=False),
        sa.Column("content",          sa.Text(),     nullable=False),
        sa.Column("citations",        postgresql.JSONB(), nullable=True),
        sa.Column("retrieval_time_ms", sa.Float(),   nullable=True),
        sa.Column("llm_time_ms",       sa.Float(),   nullable=True),
        sa.Column("total_time_ms",     sa.Float(),   nullable=True),
        sa.Column("model_used",        sa.String(100), nullable=True),
        sa.Column("has_answer",        sa.Boolean(), nullable=True),
        sa.Column("created_at",        sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_messages_conversation_id",      "messages", ["conversation_id"],              unique=False)
    op.create_index("ix_messages_conversation_created", "messages", ["conversation_id", "created_at"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id",            sa.String(36), primary_key=True),
        sa.Column("user_id",       sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("action",        sa.String(60), nullable=False),
        sa.Column("resource_type", sa.String(60), nullable=True),
        sa.Column("resource_id",   sa.String(36), nullable=True),
        sa.Column("timestamp",     sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("ip_address",    sa.String(45), nullable=True),
        sa.Column("user_agent",    sa.String(500), nullable=True),
        sa.Column("log_metadata",  postgresql.JSONB(), nullable=True),
    )
    op.create_index("ix_audit_logs_user_id",   "audit_logs", ["user_id"],  unique=False)
    op.create_index("ix_audit_logs_action",    "audit_logs", ["action"],   unique=False)
    op.create_index("ix_audit_logs_timestamp", "audit_logs", ["timestamp"], unique=False)
    op.create_index("ix_audit_logs_user_ts",      "audit_logs", ["user_id",       "timestamp"],   unique=False)
    op.create_index("ix_audit_logs_action_ts",    "audit_logs", ["action",        "timestamp"],   unique=False)
    op.create_index("ix_audit_logs_resource",     "audit_logs", ["resource_type", "resource_id"], unique=False)


def downgrade() -> None:
    # Drop in reverse dependency order
    op.drop_table("audit_logs")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("document_versions")
    op.drop_table("document_permissions")
    op.drop_table("documents")
    op.drop_table("sessions")
    op.drop_table("otp_codes")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("permissions")
    op.drop_table("roles")
    op.drop_table("users")
    # Drop enums
    op.execute("DROP TYPE IF EXISTS message_role_enum")
    op.execute("DROP TYPE IF EXISTS document_status_enum")
    op.execute("DROP TYPE IF EXISTS classification_enum")
    op.execute("DROP TYPE IF EXISTS role_enum")
